In [35]:
import pandas as pd 

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [37]:
df.head(2)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0

In [38]:
pd.__version__

'2.3.1'

In [39]:
df.shape[0]

2160

## Q3

In [40]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

### Q3 : 27 Different laptop brands 

In [41]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Q4 3 columns have at least one value null in them. 

In [42]:
df.groupby('Brand')['Final Price'].max()

Brand
Acer                3691.00
Alurin               869.00
Apple               3849.00
Asus                5758.14
Deep Gaming         1639.01
Dell                3936.00
Denver               329.95
Dynabook Toshiba    1805.01
Gigabyte            3799.00
HP                  5368.77
Innjoo               431.38
Jetwing              469.27
LG                  2399.00
Lenovo              5018.14
MSI                 7150.47
Medion              3799.00
Microsoft           3747.91
Millenium           2312.71
PcCom               1949.90
Primux               599.41
Prixton              329.95
Razer               4999.01
Realme               999.00
Samsung             3699.01
Thomson              436.56
Toshiba              799.00
Vant                1217.01
Name: Final Price, dtype: float64

### Q5 the max final price for a dell laptop is 3936.00

### Q6
For the question five we have some null values. so the best idea or an idea to tackle that is fill column with mean or meadian values

In [43]:
df.Screen.median()

np.float64(15.6)

In [61]:
mode = df['Screen'].mode()
mode

0    15.6
Name: Screen, dtype: float64

In [54]:
df.Screen.mean()

np.float64(15.168112244897959)

In [64]:
df['Screen']=df['Screen'].fillna(mode[0])

In [65]:
df['Screen'].isnull().sum()

np.int64(0)

In [62]:
type(mode)

pandas.core.series.Series

In [58]:
mode = df['Screen'].mode()
print(mode)

0    15.6
Name: Screen, dtype: float64


In [63]:
mode[0]

np.float64(15.6)

In [66]:
df.Screen.median()

np.float64(15.6)

### No the median hasn't changed after updating the nan values 

In [73]:
Innjoo = df[

    (df['Brand'] == 'Innjoo')
]

In [75]:
Innjoo[['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [78]:
X =Innjoo[['RAM','Storage','Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [115]:
import numpy as np
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [116]:
trans_X = X.T
XTX = trans_X.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [117]:

inv_XTX= np.linalg.inv(XTX)
inv_XTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [118]:
w = inv_XTX.dot(trans_X)
w

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [119]:
w = w*y
w

array([[ 289.28183831, -163.28302487, -325.17111146,  134.62818528,
          52.44041848,   57.68446033],
       [  -1.21170793,    3.83576374,    1.00713386,   -1.59921842,
          -0.76387432,   -0.84026175],
       [ -96.49448601,   35.07282588,  137.12712814,  -27.18972029,
          -1.53546111,   -1.68900722]])

In [120]:
w.sum()

np.float64(91.29988062995548)

91.30