In [3]:
import numpy as np 

In [4]:
u = np.array([1,2,3,4,5])

In [5]:
v = np.array([10,221,30,48,54])

In [6]:
v.shape

(5,)

In [7]:
v.shape[0]
u.shape[0]

5

In [8]:
def vector_to_vector_mul(u,v):
    assert u.shape[0]== v.shape[0]

    n = u.shape[0]
    result = 0 
    
    for i in range(n):
        result = u[i] * v[i] + result 
    return result 
        

In [9]:
vector_to_vector_mul(u,v)

np.int64(1004)

In [10]:
u.dot(v)

np.int64(1004)

In [11]:
X = np.random.randint(low=0, high=10, size=(4,4) )
X

array([[1, 4, 7, 8],
       [5, 4, 3, 5],
       [4, 4, 4, 7],
       [6, 8, 1, 0]])

In [12]:
Y = np.array([2,4,6,8])
Y

array([2, 4, 6, 8])

In [13]:
def matrix_to_vector_mul(X,Y):
    assert X.shape[0] == Y.shape[0]
    num_rows = X.shape[0]

    result = np.zeros(num_rows)

    for i in range (num_rows):
        result[i] = vector_to_vector_mul(X[i],Y)
    return result
        

In [14]:
X[1]

array([5, 4, 3, 5])

In [15]:
matrix_to_vector_mul(X,Y)

array([124.,  84., 104.,  50.])

In [16]:
X.dot(Y)

array([124,  84, 104,  50])

In [24]:
U  = np.random.randint(low=0, high=25, size=(4,4) ) 
V = np.random.randint(low=0, high=10, size=(4,4) )
print(f"{U}\n{V}")

[[ 0 14 14 17]
 [ 1 14  1 13]
 [ 4 11  7 16]
 [ 5 22  0 18]]
[[2 2 3 3]
 [4 5 3 3]
 [7 3 1 8]
 [4 1 1 1]]


In [27]:
def matrix_to_matrix_mul(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_to_vector_mul(U,vi)
        result[:,i] = Uvi
    return result         

In [28]:
matrix_to_matrix_mul(U,V)

array([[222., 129.,  73., 171.],
       [117.,  88.,  59.,  66.],
       [165., 100.,  68., 117.],
       [170., 138.,  99.,  99.]])

In [29]:
U.dot(V)

array([[222, 129,  73, 171],
       [117,  88,  59,  66],
       [165, 100,  68, 117],
       [170, 138,  99,  99]])

## Identity matrix 

In [32]:
ve=np.eye(4)

In [31]:
np.eye(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(100, 100))

In [33]:
V.dot(ve)

array([[2., 2., 3., 3.],
       [4., 5., 3., 3.],
       [7., 3., 1., 8.],
       [4., 1., 1., 1.]])

## Inverse of a matrix

In [51]:
V = np.random.randint(low=0, high=10, size=(4,4) )
v_inv=np.linalg.inv(V)
v_inv

array([[-0.7173913 ,  1.97826087, -0.5       ,  0.56521739],
       [ 1.80434783, -4.36956522,  1.16666667, -1.39130435],
       [-0.02173913, -0.15217391,  0.16666667, -0.04347826],
       [-0.30434783,  0.86956522, -0.33333333,  0.39130435]])

In [55]:
result=v_inv.dot(V)
result

array([[ 1.00000000e+00, -1.33226763e-15, -2.77555756e-15,
        -2.55351296e-15],
       [ 3.55271368e-15,  1.00000000e+00,  4.44089210e-15,
         6.21724894e-15],
       [ 6.24500451e-17, -1.38777878e-17,  1.00000000e+00,
         6.93889390e-18],
       [-4.99600361e-16, -3.33066907e-16, -5.55111512e-17,
         1.00000000e+00]])

this crazy ass numbers is just floating point presicion issues 

In [58]:
result[np.abs(result) < 1e-15] = 0

In [59]:
print(result)

[[ 1.00000000e+00 -1.33226763e-15 -2.77555756e-15 -2.55351296e-15]
 [ 3.55271368e-15  1.00000000e+00  4.44089210e-15  6.21724894e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
