In [1]:
import numpy as np 

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(10,69)

array([69, 69, 69, 69, 69, 69, 69, 69, 69, 69])

In [7]:
list = [89,23,34,231,43,7,6,88]

In [9]:
a = np.array(list)

In [10]:
a[2]

np.int64(34)

In [12]:
a[2] = 69
a[2]

np.int64(69)

In [15]:
np.arange(10) #upto 10 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [21]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

## Multi-Dimentional arrays

In [24]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
n= np.array([[1,2,3],
           [90,80,89],
           [56,34,69]])

In [32]:
n[0,1]

np.int64(2)

In [33]:
n[0,1]=999

In [34]:
n[0,1]

np.int64(999)

In [35]:
n[1] #get the rows

array([90, 80, 89])

In [37]:
n[:,2] #to get columns

array([ 3, 89, 69])

In [38]:
n[:,2] = [1,1,1]

In [39]:
n[:,2]

array([1, 1, 1])

In [40]:
n

array([[  1, 999,   1],
       [ 90,  80,   1],
       [ 56,  34,   1]])

## Randomly generated arrays

In [41]:
np.random.rand(5,2)

array([[0.96234775, 0.58833618],
       [0.72177094, 0.64624449],
       [0.94196031, 0.92773062],
       [0.36829745, 0.18412668],
       [0.75530314, 0.28144038]])

In [43]:
np.random.seed(10)   #we use the seed to fix the random. I mean if we run this again we will get the  same numbers
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [44]:
np.random.randn(5,2)

array([[ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737],
       [-0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761]])

In [45]:
100*np.random.rand(5,2)

array([[54.2544368 , 14.21700476],
       [37.33407601, 67.41336151],
       [44.18331744, 43.40139933],
       [61.77669785, 51.31382426],
       [65.03971819, 60.10389534]])

In [48]:
np.random.randint(low=0,high=100,size=(5,2))

array([[23, 94],
       [11, 28],
       [74, 88],
       [ 9, 15],
       [18, 80]])

## Element-Wise operations

In [50]:
a = np.arange(5)
a 

array([0, 1, 2, 3, 4])

In [64]:
c = a + 1 

In [52]:
a - 1 

array([-1,  0,  1,  2,  3])

In [53]:
a - 1  * 100

array([  0, 100, 200, 300, 400])

In [55]:
(a + 1)  * 100

array([100, 200, 300, 400, 500])

In [58]:
b = ((a + 1)  * 100)**2

In [59]:
a + b 

array([ 10000,  40001,  90002, 160003, 250004])

## Comparison operations

In [62]:
b >= 100000

array([False, False, False,  True,  True])

In [63]:
a > b

array([False, False, False, False, False])

In [66]:
a [a<c] #accesing the a array with boolean array. 

array([0, 1, 2, 3, 4])

In [67]:
b.min()

np.int64(10000)

In [68]:
a.sum()

np.int64(10)

In [70]:
a.mean()

np.float64(2.0)

In [71]:
a.std()

np.float64(1.4142135623730951)